dist: bionic
sudo: required

services:
  - docker

# change to 'minimal' when 3.7 is the default
language: python
# need 3.7 for `PYTHONUTF8` env var support
python: "3.7"

env:
  - PYTHONUTF8=1

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel

script:
  - bazel version
  - ./scripts/ci.sh
