sudo: required
dist: trusty
language: generic
before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl
  # java
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x219BD9C9
  - sudo sh -c 'echo "deb http://repos.azulsystems.com/ubuntu stable main" > /etc/apt/sources.list.d/zulu.list'
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends zulu-8=8.21.0.1
  - java -version
  # docker
  - curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get purge docker-engine || true
  - sudo apt-get install -y --no-install-recommends docker-ce=17.03.0~ce-0~ubuntu-trusty
  - sudo usermod -aG docker $USER
  - docker -v
  # bazel
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install bazel=0.5.1
  - bazel version
install:
script:
  - bazel fetch //test/... || true
  - bazel build //test/...
  # too many random failures with sandboxing enabled
  - bazel test --strategy=TestRunner=standalone --verbose_failures //test/...
after_script:
addons:
  artifacts:
    paths:
      - bazel-testlogs/
    target_paths: $TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
